import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import StoreProvider from "@/providers/store-provider";
import { fetchDataFromApi } from "@/utils/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await fetchDataFromApi("/categories?populate=*");

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header categories={categories.data} />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
